spring:
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5455/flyway-test
    username: postgresUser
    password: postgresPW
  flyway:
    enabled: true
    baselineOnMigrate: true